# Generated by Django 5.0.3 on 2024-09-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_rambutanpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RambutanPost',
        ),
    ]
