# Generated by Django 5.0.3 on 2024-09-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
