# Generated by Django 5.0.3 on 2024-09-28 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='warehouse.farmerdetails')),
            ],
        ),
    ]
