# Generated by Django 5.0.3 on 2024-09-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
