# Generated by Django 5.0.3 on 2024-10-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
