# Generated by Django 5.0.3 on 2024-10-06 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0021_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='rambutan_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.rambutanpost'),
            preserve_default=False,
        ),
    ]
