# Generated by Django 5.0.3 on 2024-10-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0022_orderitem_rambutan_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='rambutanpost',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rambutanpost',
            name='quantity_left',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
