# Generated by Django 5.0.3 on 2024-10-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0023_rambutanpost_is_available_rambutanpost_quantity_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerdetails',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='farmerdetails',
            name='total_trees',
        ),
        migrations.RemoveField(
            model_name='farmerdetails',
            name='tree_variety',
        ),
    ]
